//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DataAccessLayer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Log4Net : global::System.Configuration.ApplicationSettingsBase {
        
        private static Log4Net defaultInstance = ((Log4Net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Log4Net())));
        
        public static Log4Net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
